# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [1]:
def pl(l): # 輸出字串
    if l.ndim == 1:
        s = str(l.ndim) + "D"        
    else:        
        s = str(l.ndim) + "D"        
    print(f'輸入的:{l}是{s}陣列')
    print(f'{s}陣列的類別是{type(l)}')
    print(f'{s}第一個儲存值:{l[0]}\n{s}第一個儲存值類別:{type(l[0])}')
    print(f'使用list({s})轉換後:')    
    print(f'list({s})的數值:{(list(l))}\nlist({s})的類別:{type(list(l))} \
        \nlist({s})第一個儲存值:{list(l)[0]}\nlist({s})第一個儲存值類別:{type(list(l)[0])}')
    print(f'使用{s}.tolist()轉換後:')
    print(f'{s}.tolist()值:{l.tolist()}\n{s}.tolist()類別:{type(l.tolist())} \
          \n{s}.tolist()第一個儲存值:{l.tolist()[0]}\n{s}.tolist()第一個儲存值類別:{type(l.tolist()[0])}')
    print(f'list({s})和{s}.tolist()第一個值是否相同:{list(l)[0]==l.tolist()[0]}')
    print(f'list({s})和{s}.tolist()第一個值類別是否相同:{type(list(l)[0])==type(l.tolist()[0])}')
    
    """ #1
    執行結論
    list(array):
        一次只下降一個維度,np儲存值類別不變
    array.tolist()
        儲存值類別改變,list型態及儲存基本型態
    """

import numpy as np
a = np.arange(15)
b = np.arange(15).reshape(3,5)
c = np.arange(36).reshape(3,4,3)

In [2]:
pl(a)

輸入的:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]是1D陣列
1D陣列的類別是<class 'numpy.ndarray'>
1D第一個儲存值:0
1D第一個儲存值類別:<class 'numpy.int32'>
使用list(1D)轉換後:
list(1D)的數值:[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
list(1D)的類別:<class 'list'>         
list(1D)第一個儲存值:0
list(1D)第一個儲存值類別:<class 'numpy.int32'>
使用1D.tolist()轉換後:
1D.tolist()值:[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
1D.tolist()類別:<class 'list'>           
1D.tolist()第一個儲存值:0
1D.tolist()第一個儲存值類別:<class 'int'>
list(1D)和1D.tolist()第一個值是否相同:True
list(1D)和1D.tolist()第一個值類別是否相同:False


In [3]:
pl(b)

輸入的:[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]是2D陣列
2D陣列的類別是<class 'numpy.ndarray'>
2D第一個儲存值:[0 1 2 3 4]
2D第一個儲存值類別:<class 'numpy.ndarray'>
使用list(2D)轉換後:
list(2D)的數值:[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
list(2D)的類別:<class 'list'>         
list(2D)第一個儲存值:[0 1 2 3 4]
list(2D)第一個儲存值類別:<class 'numpy.ndarray'>
使用2D.tolist()轉換後:
2D.tolist()值:[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]
2D.tolist()類別:<class 'list'>           
2D.tolist()第一個儲存值:[0, 1, 2, 3, 4]
2D.tolist()第一個儲存值類別:<class 'list'>
list(2D)和2D.tolist()第一個值是否相同:[ True  True  True  True  True]
list(2D)和2D.tolist()第一個值類別是否相同:False


In [4]:
pl(c)

輸入的:[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]是3D陣列
3D陣列的類別是<class 'numpy.ndarray'>
3D第一個儲存值:[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
3D第一個儲存值類別:<class 'numpy.ndarray'>
使用list(3D)轉換後:
list(3D)的數值:[array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]]), array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]]), array([[24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35]])]
list(3D)的類別:<class 'list'>         
list(3D)第一個儲存值:[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
list(3D)第一個儲存值類別:<class 'numpy.ndarray'>
使用3D.tolist()轉換後:
3D.tolist()值:[[[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]], [[12, 13, 14], [15, 16, 17], [18, 19, 20], [21, 22, 23]], [[24, 25, 26], [27, 28, 29], [30, 31, 32], [33, 34, 35]]]
3D.tolist()類別:<class 'list'>           
3D.tolist()第一個儲存值:[[0, 1, 2], [3, 4, 5], 

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [5]:
# 記得先 Import 正確的套件

import numpy as np

In [6]:
def np_att(inp): # np的屬性
    print(inp)
    print(inp.ndim)
    print(inp.shape)
    print(inp.size)
    print(inp.dtype)
    print(inp.itemsize)
    print(len(inp))
    print(type(inp))

In [7]:
a = np.random.randint(10, size=6) #2

np_att(a)

[8 1 0 4 4 8]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [8]:
b = np.random.randint(10, size=(3,4)) #2

np_att(b)

[[6 0 7 4]
 [6 0 5 2]
 [4 8 2 5]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


In [9]:
c = np.random.randint(10, size=(2,3,2)) #2

np_att(c)

[[[2 2]
  [7 0]
  [9 4]]

 [[1 6]
  [3 4]
  [4 0]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [10]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[2, 7, 7, 3, 5, 9]
[2, 7, 7, 3, 5, 9]


In [11]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[4, 6, 8, 5], [0, 5, 1, 7], [2, 6, 6, 6]]
[array([4, 6, 8, 5]), array([0, 5, 1, 7]), array([2, 6, 6, 6])]


In [12]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[4, 5], [3, 9], [1, 1]], [[3, 7], [3, 4], [6, 0]]]
[array([[4, 5],
       [3, 9],
       [1, 1]]), array([[3, 7],
       [3, 4],
       [6, 0]])]


In [13]:
def tolist(iterable): #3
    if iterable.ndim == 1:
        iterable = list(iterable)
        return [int(i) for i in iterable] # 限定作業使用
    return [tolist(i) for i in iterable]

a = np.random.randint(10, size=6)
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
print("a",tolist(a))
print("b",tolist(b))
print("c",tolist(c))

a [2, 1, 1, 4, 3, 5]
b [[8, 7, 6, 1], [7, 3, 2, 7], [4, 4, 5, 7]]
c [[[5, 1], [4, 0], [2, 0]], [[3, 0], [9, 1], [6, 2]]]


In [14]:
def check_np_type(s,num):
    print_list = []
    print_list.append(f"{s}[0]={num[0]},\t{s}[0] type:{type(num[0])}")
    print_list.append(f"list({s}[0])={list(num)[0]},\tlist({s}[0]) type:{type(list(num)[0])}")
    print_list.append(f"{s}[0].tolist()={num[0].tolist()},\t{s}[0].tolist() type:{type(num[0].tolist())}")
    print_list.append(f"tolist({s}[0])={tolist(num)[0]},\ttolist({s}[0]) type:{type(tolist(num)[0])}")
    print_list.append(f"{s}[0].tolist()和tolist({s}[0]值是否相同:{num[0].tolist()==tolist(num)[0]}")
    print_list.append(f"{s}[0].tolist()和tolist({s}[0]類別是否相同:{type(num[0].tolist())==type(tolist(num)[0])}")
    for i in print_list:
        print(i)

def tolist(iterable):
    if iterable.ndim == 1:
        iterable = list(iterable)
        return [int(i) for i in iterable] # 限定作業使用
    return [tolist(i) for i in iterable]

a = np.random.randint(10, size=6)
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
print("a",tolist(a))
print("b",tolist(b))
print("c",tolist(c))
print("="*50," 各轉換型態比較")
print("a:\n")
check_np_type("a",a)
print("b:\n")
check_np_type("b",b)
print("c:\n")
check_np_type("c",b)

a [1, 7, 3, 5, 6, 1]
b [[2, 9, 9, 1], [1, 8, 5, 2], [0, 3, 6, 1]]
c [[[1, 5], [6, 0], [2, 7]], [[1, 5], [5, 7], [2, 6]]]
==================================================  各轉換型態比較
a:

a[0]=1,	a[0] type:<class 'numpy.int32'>
list(a[0])=1,	list(a[0]) type:<class 'numpy.int32'>
a[0].tolist()=1,	a[0].tolist() type:<class 'int'>
tolist(a[0])=1,	tolist(a[0]) type:<class 'int'>
a[0].tolist()和tolist(a[0]值是否相同:True
a[0].tolist()和tolist(a[0]類別是否相同:True
b:

b[0]=[2 9 9 1],	b[0] type:<class 'numpy.ndarray'>
list(b[0])=[2 9 9 1],	list(b[0]) type:<class 'numpy.ndarray'>
b[0].tolist()=[2, 9, 9, 1],	b[0].tolist() type:<class 'list'>
tolist(b[0])=[2, 9, 9, 1],	tolist(b[0]) type:<class 'list'>
b[0].tolist()和tolist(b[0]值是否相同:True
b[0].tolist()和tolist(b[0]類別是否相同:True
c:

c[0]=[2 9 9 1],	c[0] type:<class 'numpy.ndarray'>
list(c[0])=[2 9 9 1],	list(c[0]) type:<class 'numpy.ndarray'>
c[0].tolist()=[2, 9, 9, 1],	c[0].tolist() type:<class 'list'>
tolist(c[0])=[2, 9, 9, 1],	tolist(c[0]) type:<class 'list'>
c[0

In [15]:
def cpt(npt): # 確認型別
    print(npt,type(npt))    
    print(npt.tolist(),type(npt.tolist()))
    print(tolist(npt),type(tolist(npt)))
    a=npt
    b=npt.tolist()
    c=tolist(npt)
    print(a[0],type(a[0]))
    print(b[0],type(b[0]))
    print(c[0],type(c[0]))

In [16]:
a = np.random.randint(10, size=6)

cpt(a)

[7 1 2 0 2 2] <class 'numpy.ndarray'>
[7, 1, 2, 0, 2, 2] <class 'list'>
[7, 1, 2, 0, 2, 2] <class 'list'>
7 <class 'numpy.int32'>
7 <class 'int'>
7 <class 'int'>


In [17]:
b = np.random.randint(10, size=(3,4)) 

cpt(b)

[[7 9 8 9]
 [7 5 6 8]
 [7 1 1 5]] <class 'numpy.ndarray'>
[[7, 9, 8, 9], [7, 5, 6, 8], [7, 1, 1, 5]] <class 'list'>
[[7, 9, 8, 9], [7, 5, 6, 8], [7, 1, 1, 5]] <class 'list'>
[7 9 8 9] <class 'numpy.ndarray'>
[7, 9, 8, 9] <class 'list'>
[7, 9, 8, 9] <class 'list'>


In [18]:
c = np.random.randint(10, size=(2,3,2)) 

cpt(c)

[[[7 3]
  [0 9]
  [2 4]]

 [[6 5]
  [8 0]
  [3 1]]] <class 'numpy.ndarray'>
[[[7, 3], [0, 9], [2, 4]], [[6, 5], [8, 0], [3, 1]]] <class 'list'>
[[[7, 3], [0, 9], [2, 4]], [[6, 5], [8, 0], [3, 1]]] <class 'list'>
[[7 3]
 [0 9]
 [2 4]] <class 'numpy.ndarray'>
[[7, 3], [0, 9], [2, 4]] <class 'list'>
[[7, 3], [0, 9], [2, 4]] <class 'list'>
