# [作業目標]

1. [簡答題] 請問 type(...) 跟 a.dtype 這兩個語法有什麼不同？

```
print('type(a): ', type(a))
print('a.dtype: ', a.dtype)
```

2. 請撰寫一個判斷 a 的元素是否等於指定資料型態的函式

3. [簡答題] 承上題，請判斷下列三種寫法為何不正確？

```
def is_dtype(a, t):
    return a.dtype is t

def is_dtype(a, t):
    return type(a) == np.dtype(t)

def is_dtype(a, t):
    return type(a) is np.dtype(t)
```

# 作業 

### 1. [簡答題] 請問 type(...) 跟 a.dtype 這兩個語法有什麼不同？

```
print('type(a): ', type(a))
print('a.dtype: ', a.dtype)
```


In [1]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print('a:',a)
print('type(a): ', type(a))
print('type(a[0][0]): ', type(a[0][0]))
print('a.dtype: ', a.dtype)
print(f'type(a[0][0]) == a.dtype return {type(a[0][0]) == a.dtype}')

a: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
type(a):  <class 'numpy.ndarray'>
type(a[0][0]):  <class 'numpy.int32'>
a.dtype:  int32
type(a[0][0]) == a.dtype return True


### 2. 請撰寫一個判斷 a 的元素是否等於指定資料型態的函式，並且通過測試。



In [2]:
# 記得先 Import 正確的套件

import numpy as np

In [3]:
def is_dtype(a, t):
    return a.dtype is np.dtype(t) 

In [4]:
a = np.random.randint(10, size=6) 

# 測試一
print(is_dtype(a, 'int')) # True

# 測試二
print(is_dtype(a, np.int)) # True

# 測試三
print(is_dtype(a, np.dtype('int'))) # True

True
True
True


In [5]:
def is_dtype(a, t):
    print(f"a is {a}\ntype({a}) is {type(a)}\n{a}.dtype is {a.dtype},\nt is {t},type({t}) is {type(t)} \
            \nnp.dtype({t}) is {np.dtype(t)}")
    return a.dtype is np.dtype(t)

import numpy as np
a = np.random.randint(10, size=6) 

# 測試一
print('Ans 1:a.dtype is np.dtype(t) return ',is_dtype(a, 'int')) # True

# 測試二
print('Ans 2:a.dtype is np.dtype(t) return ',is_dtype(a, np.int)) # True

# 測試三
print('Ans 3:a.dtype is np.dtype(t) return ',is_dtype(a, np.dtype('int'))) # True

a is [2 9 6 6 2 5]
type([2 9 6 6 2 5]) is <class 'numpy.ndarray'>
[2 9 6 6 2 5].dtype is int32,
t is int,type(int) is <class 'str'>             
np.dtype(int) is int32
Ans 1:a.dtype is np.dtype(t) return  True
a is [2 9 6 6 2 5]
type([2 9 6 6 2 5]) is <class 'numpy.ndarray'>
[2 9 6 6 2 5].dtype is int32,
t is <class 'int'>,type(<class 'int'>) is <class 'type'>             
np.dtype(<class 'int'>) is int32
Ans 2:a.dtype is np.dtype(t) return  True
a is [2 9 6 6 2 5]
type([2 9 6 6 2 5]) is <class 'numpy.ndarray'>
[2 9 6 6 2 5].dtype is int32,
t is int32,type(int32) is <class 'numpy.dtype'>             
np.dtype(int32) is int32
Ans 3:a.dtype is np.dtype(t) return  True


In [6]:
def is_dtype(a, t):
    print(f"a is {a}\ntype({a}) is {type(a)}\n{a}.dtype is {a.dtype},\nt is {t},type({t}) is {type(t)} \
            \nnp.dtype({t}) is {np.dtype(t)}")
    return a.dtype == np.dtype(t)

import numpy as np
a = np.random.randint(10, size=6) 

# 測試一
print('Ans 1:a.dtype == np.dtype(t) return ',is_dtype(a, 'int')) # True

# 測試二
print('Ans 2:a.dtype == np.dtype(t) return ',is_dtype(a, np.int)) # True

# 測試三
print('Ans 3:a.dtype == np.dtype(t) return ',is_dtype(a, np.dtype('int'))) # True

a is [2 1 0 4 0 8]
type([2 1 0 4 0 8]) is <class 'numpy.ndarray'>
[2 1 0 4 0 8].dtype is int32,
t is int,type(int) is <class 'str'>             
np.dtype(int) is int32
Ans 1:a.dtype == np.dtype(t) return  True
a is [2 1 0 4 0 8]
type([2 1 0 4 0 8]) is <class 'numpy.ndarray'>
[2 1 0 4 0 8].dtype is int32,
t is <class 'int'>,type(<class 'int'>) is <class 'type'>             
np.dtype(<class 'int'>) is int32
Ans 2:a.dtype == np.dtype(t) return  True
a is [2 1 0 4 0 8]
type([2 1 0 4 0 8]) is <class 'numpy.ndarray'>
[2 1 0 4 0 8].dtype is int32,
t is int32,type(int32) is <class 'numpy.dtype'>             
np.dtype(int32) is int32
Ans 3:a.dtype == np.dtype(t) return  True


### 3. [簡答題] 承上題，請判斷下列三種寫法為何不正確？

```
def is_dtype(a, t):
    return a.dtype is t

def is_dtype(a, t):
    return type(a) == np.dtype(t)

def is_dtype(a, t):
    return type(a) is np.dtype(t)
```

In [7]:
def is_dtype(a, t):
    print(f"a is {a}\ntype({a}) is {type(a)}\n{a}.dtype is {a.dtype},\nt is {t},type({t}) is {type(t)}")
    return a.dtype is t

import numpy as np
a = np.random.randint(10, size=6) 

# 測試一
print('Ans 1:a.dtype is t return ',is_dtype(a, 'int'),'\n') # False

# 測試二
print('Ans 2:a.dtype is t return ',is_dtype(a, np.int),'\n') # False

# 測試三
print('Ans 3:a.dtype is t return ',is_dtype(a, np.dtype('int')),'\n') # True

a is [1 4 5 4 6 5]
type([1 4 5 4 6 5]) is <class 'numpy.ndarray'>
[1 4 5 4 6 5].dtype is int32,
t is int,type(int) is <class 'str'>
Ans 1:a.dtype is t return  False 

a is [1 4 5 4 6 5]
type([1 4 5 4 6 5]) is <class 'numpy.ndarray'>
[1 4 5 4 6 5].dtype is int32,
t is <class 'int'>,type(<class 'int'>) is <class 'type'>
Ans 2:a.dtype is t return  False 

a is [1 4 5 4 6 5]
type([1 4 5 4 6 5]) is <class 'numpy.ndarray'>
[1 4 5 4 6 5].dtype is int32,
t is int32,type(int32) is <class 'numpy.dtype'>
Ans 3:a.dtype is t return  True 



In [8]:
def is_dtype(a, t):
    print(f"a is {a}\ntype({a}) is {type(a)}\n{a}.dtype is {a.dtype},\nt is {t},type({t}) is {type(t)}")
    return a.dtype is t

import numpy as np
a = np.random.randint(10, size=6) 

# 測試一
print('Ans 1:a[0].dtype is t return ',is_dtype(a[0], 'int'),'\n') # False

# 測試二
print('Ans 2:a[0].dtype is t return ',is_dtype(a[0], np.int),'\n') # False

# 測試三
print('Ans 3:a[0].dtype is t return ',is_dtype(a[0], np.dtype('int')),'\n') # True

a is 4
type(4) is <class 'numpy.int32'>
4.dtype is int32,
t is int,type(int) is <class 'str'>
Ans 1:a[0].dtype is t return  False 

a is 4
type(4) is <class 'numpy.int32'>
4.dtype is int32,
t is <class 'int'>,type(<class 'int'>) is <class 'type'>
Ans 2:a[0].dtype is t return  False 

a is 4
type(4) is <class 'numpy.int32'>
4.dtype is int32,
t is int32,type(int32) is <class 'numpy.dtype'>
Ans 3:a[0].dtype is t return  True 



In [9]:
def is_dtype(a, t):
    print(f"a is {a}\ntype({a}) is {type(a)}\nt is {t},type({t}) is {type(t)}\nnp.dtype({t}) is {np.dtype(t)}")
    return type(a) == np.dtype(t)

import numpy as np
a = np.random.randint(10, size=6) 

# 測試一
print('Ans 1:type(a) == np.dtype(t) return ',is_dtype(a, 'int'),'\n') # False

# 測試二
print('Ans 2:type(a) == np.dtype(t) return ',is_dtype(a, np.int),'\n') # False

# 測試三
print('Ans 3:type(a) == np.dtype(t) return ',is_dtype(a, np.dtype('int')),'\n') # False

# 測試四 numpy.int32 == int32
print('Ans 4:type(a[0]) == np.dtype(t) return ',is_dtype(a[0], 'int'),'\n') # True 

a is [9 7 2 2 0 3]
type([9 7 2 2 0 3]) is <class 'numpy.ndarray'>
t is int,type(int) is <class 'str'>
np.dtype(int) is int32
Ans 1:type(a) == np.dtype(t) return  False 

a is [9 7 2 2 0 3]
type([9 7 2 2 0 3]) is <class 'numpy.ndarray'>
t is <class 'int'>,type(<class 'int'>) is <class 'type'>
np.dtype(<class 'int'>) is int32
Ans 2:type(a) == np.dtype(t) return  False 

a is [9 7 2 2 0 3]
type([9 7 2 2 0 3]) is <class 'numpy.ndarray'>
t is int32,type(int32) is <class 'numpy.dtype'>
np.dtype(int32) is int32
Ans 3:type(a) == np.dtype(t) return  False 

a is 9
type(9) is <class 'numpy.int32'>
t is int,type(int) is <class 'str'>
np.dtype(int) is int32
Ans 4:type(a[0]) == np.dtype(t) return  True 



In [10]:
def is_dtype(a, t):
    print(f"a is {a}\ntype({a}) is {type(a)}\nt is {t},type({t}) is {type(t)}\nnp.dtype({t}) is {np.dtype(t)}")
    return type(a) is np.dtype(t)

import numpy as np
a = np.random.randint(10, size=6) 

# 測試一
print('Ans 1:type(a) is np.dtype(t) return ',is_dtype(a, 'int'),'\n') # False

# 測試二
print('Ans 2:type(a) is np.dtype(t) return ',is_dtype(a, np.int),'\n') # False

# 測試三
print('Ans 3:type(a) is np.dtype(t) return ',is_dtype(a, np.dtype('int')),'\n') # False


a is [8 0 9 7 8 8]
type([8 0 9 7 8 8]) is <class 'numpy.ndarray'>
t is int,type(int) is <class 'str'>
np.dtype(int) is int32
Ans 1:type(a) is np.dtype(t) return  False 

a is [8 0 9 7 8 8]
type([8 0 9 7 8 8]) is <class 'numpy.ndarray'>
t is <class 'int'>,type(<class 'int'>) is <class 'type'>
np.dtype(<class 'int'>) is int32
Ans 2:type(a) is np.dtype(t) return  False 

a is [8 0 9 7 8 8]
type([8 0 9 7 8 8]) is <class 'numpy.ndarray'>
t is int32,type(int32) is <class 'numpy.dtype'>
np.dtype(int32) is int32
Ans 3:type(a) is np.dtype(t) return  False 



In [11]:
def is_dtype(a, t):
    print(f"a is {a}\ntype({a}) is {type(a)}\nt is {t},type({t}) is {type(t)}\nnp.dtype({t}) is {np.dtype(t)}")
    return a is np.dtype(t)

import numpy as np
a = np.random.randint(10, size=6) 

# 測試一 numpy.int32 not is int32
print('Ans 1:a is np.dtype(t) return ',is_dtype(a.dtype, 'int'),'\n') # True   

# 測試二
print('Ans 2:a is np.dtype(t) return ',is_dtype(a.dtype, np.int),'\n') # True 

# 測試三
print('Ans 3:a is np.dtype(t) return ',is_dtype(a.dtype, np.dtype('int')),'\n') # True 


a is int32
type(int32) is <class 'numpy.dtype'>
t is int,type(int) is <class 'str'>
np.dtype(int) is int32
Ans 1:a is np.dtype(t) return  True 

a is int32
type(int32) is <class 'numpy.dtype'>
t is <class 'int'>,type(<class 'int'>) is <class 'type'>
np.dtype(<class 'int'>) is int32
Ans 2:a is np.dtype(t) return  True 

a is int32
type(int32) is <class 'numpy.dtype'>
t is int32,type(int32) is <class 'numpy.dtype'>
np.dtype(int32) is int32
Ans 3:a is np.dtype(t) return  True 



In [12]:
def is_dtype(a, t):
    print(f"a is {a}\ntype({a}) is {type(a)}\nt is {t},type({t}) is {type(t)}\nnp.dtype({t}) is {np.dtype(t)}")
    return a is np.dtype(t)

import numpy as np
a = np.random.randint(10, size=6) 

# 測試一 numpy.int32 not is int32
print('Ans 1:a[0].dtype is np.dtype(t) return ',is_dtype(a[0].dtype, 'int'),'\n') # True   

# 測試二
print('Ans 2:a[0].dtype is np.dtype(t) return ',is_dtype(a[0].dtype, np.int),'\n') # True 

# 測試三
print('Ans 3:a[0].dtype is np.dtype(t) return ',is_dtype(a[0].dtype, np.dtype('int')),'\n') # True 


a is int32
type(int32) is <class 'numpy.dtype'>
t is int,type(int) is <class 'str'>
np.dtype(int) is int32
Ans 1:a[0].dtype is np.dtype(t) return  True 

a is int32
type(int32) is <class 'numpy.dtype'>
t is <class 'int'>,type(<class 'int'>) is <class 'type'>
np.dtype(<class 'int'>) is int32
Ans 2:a[0].dtype is np.dtype(t) return  True 

a is int32
type(int32) is <class 'numpy.dtype'>
t is int32,type(int32) is <class 'numpy.dtype'>
np.dtype(int32) is int32
Ans 3:a[0].dtype is np.dtype(t) return  True 

