# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [1]:
''' 參考答案
np.zeros((2, 3)) 會產生真正的 0；np.empty((2, 3)) 會產生一個近似於 0 的陣列
np.empty 可以用於只是想要初始化，但之後就會數值覆寫過的情況。
'''

' 參考答案\nnp.zeros((2, 3)) 會產生真正的 0；np.empty((2, 3)) 會產生一個近似於 0 的陣列\nnp.empty 可以用於只是想要初始化，但之後就會數值覆寫過的情況。\n'

In [2]:
import numpy as np
a = np.zeros((2, 3))
b = np.empty((2, 3))
print(f'a 初始值:{a}')
print(f'b 初始值:{b}')

a 初始值:[[0. 0. 0.]
 [0. 0. 0.]]
b 初始值:[[2.67020237e-307 4.45047451e-308 3.22648781e-307]
 [4.45039557e-307 2.22519099e-307 3.44898841e-307]]


In [3]:
a = np.zeros((2, 3))
b = np.empty((2, 3))
print(f'a 初始值:{a}')
print(f'b 初始值:{b}') # 覆寫 a

a 初始值:[[0. 0. 0.]
 [0. 0. 0.]]
b 初始值:[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
a = np.random.rand(2, 3)
a = a * 100
b = np.empty((2, 3)) * 100
print(f'a 初始值:{a}')
print(f'b 初始值:{b}') # 覆寫 a

a 初始值:[[60.87062174 71.90025298 72.94688764]
 [85.50197247 92.47804279 48.72097754]]
b 初始值:[[60.87062174 71.90025298 72.94688764]
 [85.50197247 92.47804279 48.72097754]]


In [5]:
a = np.zeros((2, 3))
b = np.empty((2, 3))
print(f'a 初始值:{a}')
print(f'b 初始值:{b}') # 上一執行 b

a 初始值:[[0. 0. 0.]
 [0. 0. 0.]]
b 初始值:[[60.87062174 71.90025298 72.94688764]
 [85.50197247 92.47804279 48.72097754]]


<ul>
    <li>In[2] 第一次執行初始值 empty 會亂數趨近於 0</li>
    <li>In[3] 和 In[4] b 數值隨 a 變化</li>
    <li>In[5] b 數值為 I[4] 的值</li>
</ul>

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [6]:
# 記得先 Import 正確的套件

import numpy as np

a = np.random.rand(2, 3)
a = a * 100

print(a)

[[24.06918608 45.05005143 44.23050674]
 [13.73953573  9.67913265 43.17745959]]


In [7]:
# 參考解答
import numpy as np
a = np.random.rand(2, 3)
a = a * 100

print(a)
print(a.round())
print(np.round(a))

[[90.31201771 70.12011067 93.92204773]
 [82.41487189 42.01552029 57.73834773]]
[[90. 70. 94.]
 [82. 42. 58.]]
[[90. 70. 94.]
 [82. 42. 58.]]


In [8]:
def na(a,num):
    return a * 10 ** num

def pa(a): #print array
    print(f'隨機陣列:\n{a}')
    for i in range(1,3):
        ra = na(a,i)
        print(f'{10**i}倍陣列\n{ra}')
        print(f'取整數方法一:a.round()\n{ra.round()}')
        print(f'取整數方法二:np.round(a)\n{np.round(ra)}')
        
import numpy as np
a = np.random.rand(2, 3)
pa(a)

隨機陣列:
[[0.48720601 0.70772072 0.07708166]
 [0.49982177 0.44915906 0.02428563]]
10倍陣列
[[4.87206011 7.07720724 0.7708166 ]
 [4.99821768 4.49159059 0.24285632]]
取整數方法一:a.round()
[[5. 7. 1.]
 [5. 4. 0.]]
取整數方法二:np.round(a)
[[5. 7. 1.]
 [5. 4. 0.]]
100倍陣列
[[48.72060107 70.77207236  7.70816604]
 [49.98217683 44.91590591  2.42856322]]
取整數方法一:a.round()
[[49. 71.  8.]
 [50. 45.  2.]]
取整數方法二:np.round(a)
[[49. 71.  8.]
 [50. 45.  2.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [9]:
m = 20
n = 40

a = np.random.rand(2,3) * (n-m)
b =a

print(f'a:{a}')
print(f'b:{b}')
print(f'介於{m}-{n}之間:\n{(a-b % 1) + m}')

a:[[ 8.74532837 15.63092745 13.18108957]
 [19.84793741  2.46602883 10.13969391]]
b:[[ 8.74532837 15.63092745 13.18108957]
 [19.84793741  2.46602883 10.13969391]]
介於20-40之間:
[[28. 35. 33.]
 [39. 22. 30.]]
