# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [2]:
# 記得先 Import 正確的套件

import numpy as np

In [41]:
np_a = np.arange(11) + 1
print(np_a)
np_a[(np_a >= 3) & (np_a < 7)] *= -1
np_a

[ 1  2  3  4  5  6  7  8  9 10 11]


array([ 1,  2, -3, -4, -5, -6,  7,  8,  9, 10, 11])

### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [46]:
A = np.random.rand(3, 6)

print(A)
num = A[A > 0.5].size
num

[[0.09589972 0.55599752 0.2118414  0.29650667 0.04421332 0.89501265]
 [0.89375416 0.22475168 0.06120372 0.93339971 0.75918357 0.48972188]
 [0.02599176 0.76738547 0.28976635 0.59977121 0.81575247 0.53126133]]


9