# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [7]:
import numpy as np
a = np.arange(10)
print(a)
print(a.sum()) # numpy.ndarray
print(np.sum(a)) # module numpy
print(sum(a))  # module builtins

[0 1 2 3 4 5 6 7 8 9]
45
45
45


In [4]:
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers
    
    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



In [5]:
help(np.sum)

Help on function sum in module numpy:

sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
    Sum of array elements over a given axis.
    
    Parameters
    ----------
    a : array_like
        Elements to sum.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a sum is performed.  The default,
        axis=None, will sum all of the elements of the input array.  If
        axis is negative it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If axis is a tuple of ints, a sum is performed on all of the axes
        specified in the tuple instead of a single axis or all the axes as
        before.
    dtype : dtype, optional
        The type of the returned array and of the accumulator in which the
        elements are summed.  The dtype of `a` is used by default unless `a`
        has an integer dtype of less precision than the default platform
        integer.  In 

In [6]:
help(a.sum)

Help on built-in function sum:

sum(...) method of numpy.ndarray instance
    a.sum(axis=None, dtype=None, out=None, keepdims=False, initial=0, where=True)
    
    Return the sum of the array elements over the given axis.
    
    Refer to `numpy.sum` for full documentation.
    
    See Also
    --------
    numpy.sum : equivalent function



### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [ ]:
# 記得先 Import 正確的套件

import numpy as np

In [12]:
A = np.random.random((5, 5))

print(f'A:{A}\nmin:{A.min()}\nmax:{A.max()}')
A = (A-A.min()) / (A.max()-A.min())
A

A:[[0.18810398 0.81723068 0.62205384 0.52114738 0.68315102]
 [0.3994979  0.31686312 0.95364173 0.38888741 0.56298275]
 [0.51798934 0.51176355 0.32474587 0.75816027 0.08221576]
 [0.34893634 0.47143485 0.5291293  0.25251115 0.78086578]
 [0.06693567 0.70067617 0.15633083 0.37389774 0.86296798]]
min:0.06693567456535598
max:0.9536417268099008


array([[0.13664991, 0.84615978, 0.62604531, 0.51224608, 0.69494885],
       [0.37505352, 0.28186054, 1.        , 0.36308734, 0.55942674],
       [0.50868454, 0.50166329, 0.29075046, 0.77954199, 0.01723241],
       [0.31803173, 0.45618181, 0.52124785, 0.20928635, 0.80514857],
       [0.        , 0.71471317, 0.10081713, 0.34618244, 0.89774092]])

### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [27]:
np_z = np.random.random(10)
print(f'np:{np_z}\n陣列最大值 np[{np.argmax(np_z)}]\nnp_max:{np_z[np.argmax(np_z)]}')
np_z[np.argmax(np_z)] = -1
np_z

np:[0.12200759 0.89321539 0.90039073 0.95861842 0.85161116 0.90256739
 0.5751692  0.95559469 0.11004043 0.0636404 ]
陣列最大值 np[3]
np_max:0.9586184200925006


array([ 0.12200759,  0.89321539,  0.90039073, -1.        ,  0.85161116,
        0.90256739,  0.5751692 ,  0.95559469,  0.11004043,  0.0636404 ])

In [19]:
help(np.argmax)

Help on function argmax in module numpy:

argmax(a, axis=None, out=None)
    Returns the indices of the maximum values along an axis.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axis : int, optional
        By default, the index is into the flattened array, otherwise
        along the specified axis.
    out : array, optional
        If provided, the result will be inserted into this array. It should
        be of the appropriate shape and dtype.
    
    Returns
    -------
    index_array : ndarray of ints
        Array of indices into the array. It has the same shape as `a.shape`
        with the dimension along `axis` removed.
    
    See Also
    --------
    ndarray.argmax, argmin
    amax : The maximum value along a given axis.
    unravel_index : Convert a flat index into an index tuple.
    take_along_axis : Apply ``np.expand_dims(index_array, axis)``
                      from argmax to an array as if by calling max.
    
    Notes
    ----